name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
          MYSQL_USER: ${{ secrets.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd='mysqladmin ping --host=localhost' --health-interval=10s --health-timeout=5s --health-retries=3

      # Dịch vụ PHP + Nginx + Mailhog, nếu cần
      php:
        image: ${PROJECT_NAME}_php:${APP_ENV}
        ports:
          - 9000:9000
        env:
          SERVICE_NAME: php
          SERVICE_TAGS: dev
        volumes:
          - .:/var/www
        depends_on:
          - mysql

      # Mailhog (nếu cần gửi email kiểm tra)
      mailhog:
        image: mailhog/mailhog
        ports:
          - "1025:1025"
          - "8025:8025"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and test PHP application
        run: |
          docker-compose -f docker-compose.yml up -d
          docker-compose exec php composer install --no-interaction --prefer-dist --optimize-autoloader
          docker-compose exec php php artisan migrate --force
          docker-compose exec php php artisan config:cache
          docker-compose exec php php artisan route:cache

      - name: Run tests
        run: |
          docker-compose exec php ./vendor/bin/phpunit

      - name: Push to DockerHub
        if: github.ref == 'refs/heads/main'
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose push
